"""Kiwix document libraries (nautiluszim) whose videos and audio ZimiTube
plays, cut down from the real ZIMs: the listing files verbatim (or their
first items, verbatim), the files where the listing puts them, with the
mimetypes the real ZIMs give them."""

# maitre_lucas_compter_jusque_10_fr_2023-05 (nautiluszim 1.1.1): the whole
# listing, twelve PDF worksheets and one video.
LUCAS_DATABASE = 'var DATABASE = [\n{\'_id\': \'00000\', \'ti\': "Nombres en lettres jusqu\'à 10 corrigé", \'dsc\': "Corrigé Nombres en lettres jusqu\'à 10", \'aut\': \'Maître Lucas\', \'fp\': [\'nombres en lettres jusqu_à 10 corrigé.pdf\']},\n{\'_id\': \'00001\', \'ti\': "Compter jusqu\'à 10 6", \'dsc\': "Fiche d\'exercice Compter jusqu\'à 10 6", \'aut\': \'Maître Lucas\', \'fp\': [\'compter 6.pdf\']},\n{\'_id\': \'00002\', \'ti\': "Compter jusqu\'à 10 4", \'dsc\': "Fiche d\'exercice Compter jusqu\'à 10 4", \'aut\': \'Maître Lucas\', \'fp\': [\'COMPTER 4.pdf\']},\n{\'_id\': \'00003\', \'ti\': "Compter jusqu\'à 10 7", \'dsc\': "Fiche d\'exercice Compter jusqu\'à 10 7", \'aut\': \'Maître Lucas\', \'fp\': [\'comtper 7.pdf\']},\n{\'_id\': \'00004\', \'ti\': "Compter jusqu\'à 10 10", \'dsc\': "Fiche d\'exercice Compter jusqu\'à 10 10", \'aut\': \'Maître Lucas\', \'fp\': [\'compter 10.pdf\']},\n{\'_id\': \'00005\', \'ti\': "Compter jusqu\'à 10 3", \'dsc\': "Fiche d\'exercice Compter jusqu\'à 10 3", \'aut\': \'Maître Lucas\', \'fp\': [\'compter 3.pdf\']},\n{\'_id\': \'00006\', \'ti\': "Compter jusqu\'à 10 5", \'dsc\': "Fiche d\'exercice Compter jusqu\'à 10 5", \'aut\': \'Maître Lucas\', \'fp\': [\'compter 5.pdf\']},\n{\'_id\': \'00007\', \'ti\': "Nombres en lettres jusqu\'à 10", \'dsc\': "Exercices Nombres en lettres jusqu\'à 10", \'aut\': \'Maître Lucas\', \'fp\': [\'Nombres en lettres jusqu_à 10.pdf\']},\n{\'_id\': \'00008\', \'ti\': "Compter jusqu\'à 10 2", \'dsc\': "Fiche d\'exercice Compter jusqu\'à 10 2", \'aut\': \'Maître Lucas\', \'fp\': [\'compter 2.pdf\']},\n{\'_id\': \'00009\', \'ti\': "Compter jusqu\'à 10 1", \'dsc\': "Fiche d\'exercice Compter jusqu\'à 10 1", \'aut\': \'Maître Lucas\', \'fp\': [\'compter 1.pdf\']},\n{\'_id\': \'00010\', \'ti\': "Nombres en lettres jusqu\'à 10 CP - CE1 - Cycle 2", \'dsc\': "Cette vidéo à destination des élèves de Cycle 2 (CP, CE1), permet d\'apprendre à écrire les nombres en lettre jusqu\'à 10. Je propose tout d\'abord des exercices pour les distinguer puis apprendre à les écrire. \\n", \'aut\': \'Maître Lucas\', \'fp\': [\'nombres en lettres jusqu_à 10 maths cp ce1 cycle 2.mp4\']},\n{\'_id\': \'00011\', \'ti\': "Compter jusqu\'à 10 8", \'dsc\': "Fiche d\'exercice Compter jusqu\'à 10 8", \'aut\': \'Maître Lucas\', \'fp\': [\'compter 8.pdf\']},\n{\'_id\': \'00012\', \'ti\': "Compter jusqu\'à 10 9", \'dsc\': "Fiche d\'exercice Compter jusqu\'à 10 9", \'aut\': \'Maître Lucas\', \'fp\': [\'compter 9.pdf\']},\n];\n'
LUCAS_META = {"Name": "maitre_lucas_compter_jusque_10_fr", "Title": "Compter jusqu'\u00e0 10", "Language": "fra", "Scraper": "nautiluszim 1.1.1", "Creator": "Ma\u00eetre Lucas", "Publisher": "Kiwix"}
LUCAS_VIDEO = "files/nombres en lettres jusqu_\u00e0 10 maths cp ce1 cycle 2.mp4"

# youscribe_fr_audiobooks_2023-03 (nautiluszim 1.0.8): two of its 234
# audiobooks, one in eight tracks and one in one.
AUDIOBOOKS_DATABASE = 'var DATABASE = [\n{\'_id\': \'00002\', \'ti\': \'Le Chien des Baskerville\', \'dsc\': "Suite à la mort mystérieuse de Sir Charles Baskerville, Sherlock Holmes et son célèbre acolyte, le docteur Watson, sont engagés pour résoudre le mystère de la malédiction qui pèse sur la famille des Baskerville : une malédiction qui se manifesterait sous la forme d\'un chien surgissant des enfers et ", \'aut\': \'Arthur Conan Doyle\', \'fp\': [\'2909454_Doyle___Le_chien_des_Baskerville_01_a_03.ogg\', \'2909454_Doyle___Le_chien_des_Baskerville_04_et_05.ogg\', \'2909454_Doyle___Le_chien_des_Baskerville_06_et_07.ogg\', \'2909454_Doyle___Le_chien_des_Baskerville_08_et_09.ogg\', \'2909454_Doyle___Le_chien_des_Baskerville_10_et_11.ogg\', \'2909454_Doyle___Le_chien_des_Baskerville_12.ogg\', \'2909454_Doyle___Le_chien_des_Baskerville_13_et_14.ogg\', \'2909454_Doyle___Le_chien_des_Baskerville_15.ogg\']},\n{\'_id\': \'00005\', \'ti\': \'Le Chat Botté\', \'dsc\': \'Illustration musicale :\\nMichael Fix : Tocatta Fugue (Bach arr. Michael Fix for solo guitar) et\\nMr Wonglepong et The Heart has Reasons (that reason cant explain) et Wil I or wont I. Last.fm\', \'aut\': \'Perrault Charles\', \'fp\': [\'2909458_Perrault___Le_Chat_Botte.ogg\']},\n];\n'
AUDIOBOOKS_META = {"Name": "youscribe_fr_audiobooks", "Title": "Audiolivres de litt\u00e9rature classique", "Language": "fra", "Scraper": "nautiluszim 1.0.8", "Creator": "YouScribe", "Publisher": "Kiwix"}

# zaya-english-duniya-marathi_mr_2020-11 (nautiluszim 1.0.5): its first two
# videos, WebM, numbered from 0 as in every nautilus library.
ZAYA_DATABASE = "var DATABASE = [\n{'_id': '0', 'ti': 'Grammar concept - Common noun Vs Proper noun', 'dsc': 'Learn the difference between common vs proper nouns', 'aut': 'Zaya', 'fp': ['en-mr_grammar-concept-common-vs-proper-nouns.webm']},\n{'_id': '1', 'ti': 'Grammar concept - Countable Vs Uncountable nouns', 'dsc': 'Learn what are countable Vs uncountable nouns', 'aut': 'Zaya', 'fp': ['en-mr_grammar-concept-countable-vs-uncountable-nouns.webm']},\n];\n"
ZAYA_META = {"Name": "zaya-english-duniya-marathi_mr", "Title": "English Duniya - Marathi", "Language": "mar", "Scraper": "nautiluszim 1.0.5", "Creator": "Zaya", "Publisher": "Kiwix"}

MP4 = b"\x00\x00\x00\x18ftypmp42\x00\x00\x00\x00mp42isom"
WEBM = b"\x1a\x45\xdf\xa3webm"
OGG = b"OggS\x00\x02" + b"\x00" * 20
PDF = b"%PDF-1.4\n%%EOF\n"
