"""Wikisource pages without #ws-data, cut from the real ZIMs (2026-07 builds).

- wikisource_sk_all_maxi_2026-07, Slovak: a work's header is a table,
  "Údaje o texte", whose cells carry the ids (<td id="ws-author">); the
  ws-title id marks the cell that says "Titulok". Its works are single
  pages. Biblia is a disambiguation page, and the tops of the trees under
  Patery_knihy_plodů_básnických/ and 460/ are not in the ZIM.
- wikisource_li_all_maxi_2026-07, Limburgish: no header at all; a book is a
  page with pages under it (Middelärcher), and the main page has some too.

Each page keeps its header verbatim and the first words of its text.
"""

WIKISOURCE_SK_PAGES = {
    'A_čija_to_chyža': ('<!DOCTYPE html><html lang="sk" dir="ltr"><head><meta charset="UTF-8"><title>A čija to chyža</title></head><body><h1 class="article-header">A čija to chyža</h1><table class="textinfo wikitable rightbox" align="right" width="300">\n\n<tbody><tr>\n<th colspan="2">Údaje o texte\n</th></tr>\n<tr>\n<td id="ws-title">Titulok</td>\n<td>A čija to chyža\n</td></tr>\n<tr>\n<td>Autor</td>\n<td id="ws-author">neznámy</td>\n</tr>\n<tr>\n<td>Zdroj</td>\n<td>ľudová pieseň</td>\n</tr>\n\n\n<tr>\n<td>Licencia</td>\n<td><span typeof="mw:File"><span><img alt="" src="./_assets_/356d87e38c378ba7b04f1f5eaf923e63.png" decoding="async" width="16" height="16" class="mw-file-element" data-file-width="196" data-file-height="196" loading="lazy"></span></span> PD SK\n</td></tr></tbody></table><p><p>A čija to chyža, stojit na dolini,<br> či je to divčatko šyje na mašyni,<br> či je to divčatko šyje na mašyni.<br> <br> Mašyna čerkoče a divčatko plače, <br> vernij sja mi vernij, mij milyj kozače,<br> vernij sja mi vernij, mij milyj koz</p></body></html>', 'A čija to chyža'),
    'Báseň': ('<!DOCTYPE html><html lang="sk" dir="ltr"><head><meta charset="UTF-8"><title>Báseň</title></head><body><h1 class="article-header">Báseň</h1><table class="textinfo wikitable rightbox" align="right" width="300">\n\n<tbody><tr>\n<th colspan="2">Údaje o texte\n</th></tr>\n<tr>\n<td id="ws-title">Titulok</td>\n<td>Báseň\n</td></tr>\n<tr>\n<td>Autor</td>\n<td id="ws-author">Autor:Jozef Tomášik-Dumín</td>\n</tr>\n<tr>\n<td>Zdroj</td>\n<td>Redakcia Dav, zima 1924 (digitalizace DAV DVA, prepis Soňa Valovičová, DAV DVA) <a rel="nofollow" class="external text" href="https://davdva.sk/dav-zima-1924-vyber-basni-a-myslienok/">Dostupné online</a></td>\n</tr>\n\n\n<tr>\n<td>Licencia</td>\n<td><span typeof="mw:File"><span><img alt="" src="./_assets_/356d87e38c378ba7b04f1f5eaf923e63.png" decoding="async" width="16" height="16" class="mw-file-element" data-file-width="196" data-file-height="196" loading="lazy"></span></span> PD old 70\n</td></tr></tbody></table><p><p>Ona v kaviarni posluhovala<br> poháre k srdcu priviňovala<br> Haja – ja –<br> Na srdci chlapčeka nosila<br> raz tak stalo sa divotvorne<br> na rúčkach chlapčeka ukazovala<br> Haja – ja –<br> Po líčkach rozkošne zasmiala sa<br> jej smiech</p></body></html>', 'Báseň'),
    'Horská_chatrč': ('<!DOCTYPE html><html lang="sk" dir="ltr"><head><meta charset="UTF-8"><title>Horská chatrč</title></head><body><h1 class="article-header">Horská chatrč</h1><table class="textinfo wikitable rightbox" align="right" width="300">\n\n<tbody><tr>\n<th colspan="2">Údaje o texte\n</th></tr>\n<tr>\n<td id="ws-title">Titulok</td>\n<td>Horská chatrč\n</td></tr>\n<tr>\n<td>Autor</td>\n<td id="ws-author">Pavol Országh Hviezdoslav</td>\n</tr>\n<tr>\n<td>Zdroj</td>\n<td><a rel="nofollow" class="external text" href="https://www.visegradliterature.net/works/hu/Pet%c5%91fi_S%c3%a1ndor-1823/Az_erdei_lak/sk/59622-Horsk%c3%a1_chatr%c4%8d?tr_id=868">visegradliterature</a></td>\n</tr>\n\n\n<tr>\n<td>Licencia</td>\n<td><span typeof="mw:File"><span><img alt="" src="./_assets_/356d87e38c378ba7b04f1f5eaf923e63.png" decoding="async" width="16" height="16" class="mw-file-element" data-file-width="196" data-file-height="196" loading="lazy"></span></span> PD old 70\n</td></tr></tbody></table><p><p>Ako srdce prvej lásky taj, tak skrýva<br> ramä bŕd chalúpku na podolku tichom;<br> nepoškodí streche jej slamenej, divá<br> keď víchrica vzteklým sem zafúkne dychom.<br> <br> Slamenú jej strechu, z rána v lesku rosy,<br> tôni šumných háj</p></body></html>', 'Horská chatrč'),
    'Hájnikova_žena': ('<!DOCTYPE html><html lang="sk" dir="ltr"><head><meta charset="UTF-8"><title>Hájnikova žena</title></head><body><h1 class="article-header">Hájnikova žena</h1><table class="textinfo wikitable rightbox" align="right" width="300">\n\n<tbody><tr>\n<th colspan="2">Údaje o texte\n</th></tr>\n<tr>\n<td id="ws-title">Titulok</td>\n<td>Hájnikova žena\n</td></tr>\n\n\n\n\n<tr>\n<td>Licencia</td>\n<td><span typeof="mw:File"><span><img alt="" src="./_assets_/356d87e38c378ba7b04f1f5eaf923e63.png" decoding="async" width="16" height="16" class="mw-file-element" data-file-width="196" data-file-height="196" loading="lazy"></span></span> PD old 70\n</td></tr></tbody></table><p>Pozdrav <p>Pozdravujem vás, lesy, hory,<br> z tej duše pozdravujem vás!<br> Čo mrcha svet v nás skvári, zmorí,<br> zrak jeho urknul, zmámila<br> lož, ohlušila presila:<br> vy k žitiu privediete zas,<br> vy vzkriesite, vy zotavíte,<br> z jat</p></body></html>', 'Hájnikova žena'),
    'Biblia': ('<!DOCTYPE html><html lang="sk" dir="ltr"><head><meta charset="UTF-8"><title>Biblia</title></head><body><h1 class="article-header">Biblia</h1><p><p> Biblia má viac významov: </p> Biblia (ekumenický preklad) Biblia (katolícky preklad) Biblia (evanjelický preklad) Biblia (Roháčkov preklad) Biblia (Botekov preklad) This article is issued from </p></body></html>', 'Biblia'),
    'Index:Nárečja_Slovenskuo.djvu': ('<!DOCTYPE html><html lang="sk" dir="ltr"><head><meta charset="UTF-8"><title>Index:Nárečja Slovenskuo.djvu</title></head><body><h1 class="article-header">Index:Nárečja Slovenskuo.djvu</h1><p>Autor Názov Nárečja Slovenskuo; alebo, Potreba písaňja v tomto nárečí Rok vydania 1846 Vydavateľstvo K. F. Wigand Obálka Strany </p></body></html>', 'Index:Nárečja Slovenskuo.djvu'),
    'Page:Nárečja_Slovenskuo.djvu/1': ('<!DOCTYPE html><html lang="sk" dir="ltr"><head><meta charset="UTF-8"><title>Page:Nárečja Slovenskuo.djvu/1</title></head><body><h1 class="article-header">Page:Nárečja Slovenskuo.djvu/1</h1><p>Táto stránka bola skontrolovaná<p>NÁREČJA SLOVENSKUO </p><p>ALEBO </p><p>POTREBA PÍSAŇJA V TOMTO NÁREČÍ </p><p>VISTAVENÁ </p><p>OD </p><p>LUDEVÍTA ŠTÚRA. </p><p>V PREŠPORKU 1846. </p><p>V tlačjarňi K. F. Wiganda. </p><p></p></body></html>', 'Page:Nárečja Slovenskuo.djvu/1'),
    'Wikizdroje:Hlavná_stránka': ('<!DOCTYPE html><html lang="sk" dir="ltr"><head><meta charset="UTF-8"><title>Wikizdroje:Hlavná stránka</title></head><body><h1 class="article-header">Wikizdroje:Hlavná stránka</h1><p>Vitajte na stránke Wikizdrojov ~ Wikisource! <p>Vitajte vo Wikizdrojoch, zbierke voľne dostupných originálnych textov v&nbsp;slovenskom jazyku. Wikizdroje obsahujú momentálne 498&nbsp;stránok. Navštívte pomocníka a&nbsp;experimentujte na pi</p></body></html>', 'Wikizdroje:Hlavná stránka'),
    'Patery_knihy_plodů_básnických/Zpievanky': ('<!DOCTYPE html><html lang="sk" dir="ltr"><head><meta charset="UTF-8"><title>Patery knihy plodů básnických/Zpievanky</title></head><body><h1 class="article-header">Patery knihy plodů básnických/Zpievanky</h1><table class="textinfo wikitable rightbox" align="right" width="300">\n\n<tbody><tr>\n<th colspan="2">Údaje o texte\n</th></tr>\n<tr>\n<td id="ws-title">Titulok</td>\n<td>Zpievanky\n</td></tr>\n<tr>\n<td>Autor</td>\n<td id="ws-author">neznámy</td>\n</tr>\n<tr>\n<td>Zdroj</td>\n<td>ľudová pieseň</td>\n</tr>\n<tr>\n<td>Dátum vzniku</td>\n<td>1892</td>\n</tr>\n\n<tr>\n<td>Licencia</td>\n<td><span typeof="mw:File"><span><img alt="" src="../_assets_/356d87e38c378ba7b04f1f5eaf923e63.png" decoding="async" width="16" height="16" class="mw-file-element" data-file-width="196" data-file-height="196" loading="lazy"></span></span> PD SK\n</td></tr></tbody></table><p>\u200bSlov. Spevů čís. 539. Zpievanky. <p>Zpievanky, zpievanky, kdeže ste sa vzaly,<br> či ste spadly neba, či ste rástly v háji?<br> Z neba sme nespadly, v háji sme nerástly,<br> ale nás mládenci a dievčence našly. </p> This article is issued f</p></body></html>', 'Patery knihy plodů básnických/Zpievanky'),
    '460/1992_Zb./1._hlava': ('<!DOCTYPE html><html lang="sk" dir="ltr"><head><meta charset="UTF-8"><title>460/1992 Zb./1. hlava</title></head><body><h1 class="article-header">460/1992 Zb./1. hlava</h1><p><p><a href="../../%C3%9Astava_Slovenskej_republiky" title="Ústava Slovenskej republiky">Ústava Slovenskej republiky</a> </p><p><a href="../../460/1992_Zb./Preambula" title="460/1992 Zb./Preambula">Preambula</a> • </p></body></html>', '460/1992 Zb./1. hlava'),
}

WIKISOURCE_LI_PAGES = {
    'Middelärcher': ('<!DOCTYPE html><html lang="li" dir="ltr"><head><meta charset="UTF-8"><title>Middelärcher</title></head><body><h1 class="article-header">Middelärcher</h1><p><p>Middelärcher is \'n book van 1857 in \'t aad Remunjs van 138 pagina\'s mit konstant dezelvende inhawd. </p> <a href="Middel%C3%A4rcher/Veurw%C3%B2rd_I" title="Middelärcher/Veurwòrd I">Middelärcher/Veurwòrd I</a> </p></body></html>', 'Middelärcher'),
    'Middelärcher/Inhawd_1': ('<!DOCTYPE html><html lang="li" dir="ltr"><head><meta charset="UTF-8"><title>Middelärcher/Inhawd 1</title></head><body><h1 class="article-header">Middelärcher/Inhawd 1</h1><p><p>Wèrk in oetveuring. Zuuch noe <a href="../Middel%C3%A4rcher" title="Middelärcher">Middelärcher</a>. </p> This article is issued from </p></body></html>', 'Middelärcher/Inhawd 1'),
    'Middelärcher/Achtewòrd': ('<!DOCTYPE html><html lang="li" dir="ltr"><head><meta charset="UTF-8"><title>Middelärcher/Achtewòrd</title></head><body><h1 class="article-header">Middelärcher/Achtewòrd</h1><p><p>Wèrk in oetveuring. Zuuch noe <a href="../Middel%C3%A4rcher" title="Middelärcher">Middelärcher</a>. </p> This article is issued from </p></body></html>', 'Middelärcher/Achtewòrd'),
    'Veurblaad': ('<!DOCTYPE html><html lang="li" dir="ltr"><head><meta charset="UTF-8"><title>Veurblaad</title></head><body><h1 class="article-header">Veurblaad</h1><p>Wèlkóm! <p> De vrie brónne veur öch ligke hie! <br> Wilkóm bie Wikibrónne. Wikibrónne is e miertalig projek det \'n verzameling van bróntekste is, die zeen te laeze in versjillende tale. Bróntekste die hie geplaats waere mótte valle ónger \'t</p></body></html>', 'Veurblaad'),
    'Veurblaad/AGL': ('<!DOCTYPE html><html lang="li" dir="ltr"><head><meta charset="UTF-8"><title>Veurblaad/AGL</title></head><body><h1 class="article-header">Veurblaad/AGL</h1><p>Wèlkóm! <p> De vrie brónne veur öch ligke hie! <br> Wèlkóm bie Wikibrónne. Wikibrónne is \'n meertalig projek det \'n verzameling van bróntekste is, die zeen te laeze in versjillende tale. Bróntekste die hie geplaats waere mótte valle ónger \'</p></body></html>', 'Veurblaad/AGL'),
    "'n_Man_&_'n_vrouw": ('<!DOCTYPE html><html lang="li" dir="ltr"><head><meta charset="UTF-8"><title>\'n Man & \'n vrouw</title></head><body><h1 class="article-header">\'n Man & \'n vrouw</h1><p>\'n Man &amp; \'n vrouw Sjriever Jack Pouls Plaats America Saort Leedteks Oetveurendje Rowwen Hèze <p>Trögk nao <a href="Indeks_van_America" title="Indeks van America">America</a>. </p> Teks <p>\'n Man, \'n vrouw en enne groete pot beer,<br> en</p></body></html>', "'n Man & 'n vrouw"),
}
